export const PASSWORD_SIZE_LIMIT = 'The password should contain from 9 to 27 characters'
export const USERNAME_SIZE_LIMIT = 'The userName should contain less than 27 characters'
export const REQUIRED = 'The field cannot be empty'
export const PASSWORD_MATCH = 'Passwords must match'
export const EMAIL_INCORRECT = 'The email is incorrect!'
